### ISSUE TITLE
How can i specify the color of the highlighted code

### ISSUE THREAD

**Issue by iosmanthus** [rianneogi/ide-cquery#11]
it seems `code highlight` in ide-cquery doesn't work but in vscode. In vscode, i can specify the color to different syntax entities. Just like the following picture shows: can i have this in ide-cquery too?
![screenshot from 2018-03-22 01-17-11](https://user-images.githubusercontent.com/16307070/37725811-c683c8e4-2d6e-11e8-8321-d927eb36ff9f.png)

**Comment by edjubuh** [comment]
That's something this plugin will have to sort of do on it's own. We're gonna need to look into how to extract the right colors so that it fits well with whatever syntax theme you're using. I've made a branch with an early prototype of parsing the semantic highlighting from cquery and applying the decorators onto the text, but some more work still needs to be done on it (specifically making the decorators do something interesting).

Here's how the official cquery VS code extension does it:  https://github.com/cquery-project/vscode-cquery/blob/master/src/extension.ts#L677-L818

**Comment by rianneogi** [comment]
Semantic Highlighting is there in ide-cquery now. I have disabled it by default, you will need to go to the settings and enable Semantic Hightlighting and Set Inactive Regions.

**Comment by rianneogi** [comment]
Closing this for now. If you find any issue with the semantic highlighting, create an new issue.

**Comment by iosmanthus** [comment]
@rianneogi  thanks
